---
title: "Plots Interactions"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Calculate model
```{r}
multinom_int <- multinom(numcars ~ region2 + numlic + I(numlic^2) + region2:numlic + region2:I(numlic^2) + income_numerical +I(income_numerical^2)+ region2:income_numerical + region2:I(income_numerical^2) + quali_nv + region2:quali_nv + CSyes + region2:CSyes + workers+ I(workers^2)+region2:workers +region2:I(workers^2)+ triplength_avg+ I(triplength_avg^2)+ region2:triplength_avg+ region2:I(triplength_avg^2) + log(nummots1) + region2:log(nummots1) +housing_type + region2:housing_type+ garage +region2:garage+ quali_opnv + region2:quali_opnv+oldHH + region2:oldHH +CSmultiple+region2:CSmultiple+ hh_children + region2:hh_children + metro28 + parttime + I(parttime^2) + region2:parttime+train28 +numped + I(numped^2) + region2:numped + region2:I(numped^2) + bus28, data = HH_dt_2_out, maxit=700)


multinom_int <- multinom(numcars ~ region2 + numlic + I(numlic^2) + region2:numlic + region2:I(numlic^2) + income_numerical +I(income_numerical^2)+ region2:income_numerical + region2:I(income_numerical^2) + quali_nv + region2:quali_nv+CSyes + region2:CSyes + workers+ I(workers^2)+ region2:workers + triplength_avg+ I(triplength_avg^2)+ region2:triplength_avg+ region2:I(triplength_avg^2) + log(nummots1) + housing_type + garage + quali_opnv + oldHH + region2:oldHH+ CSmultiple+ hh_children + region2:hh_children + metro28 +tripsavg + parttime + train28 +numped + I(numped^2) + region2:numped + region2:I(numped^2) +bus28, data = HH_dt_2_out, maxit=700)

fm_int <- formula(numcars ~  1|region2 + numlic + I(numlic^2) + region2:numlic + region2:I(numlic^2) + income_numerical +I(income_numerical^2)+ region2:income_numerical + region2:I(income_numerical^2) + quali_nv + region2:quali_nv+CSyes + region2:CSyes + workers+ I(workers^2)+ region2:workers + triplength_avg+ I(triplength_avg^2)+ region2:triplength_avg+ region2:I(triplength_avg^2) + log(nummots1) + housing_type + garage + quali_opnv + share2039 + I(share2039^2)  +  region2:share2039 + region2:I(share2039^2) + share4064 + CSmultiple+ hh_children + region2:hh_children + metro28 +tripsavg + parttime + train28 +numped + I(numped^2) + region2:numped + region2:I(numped^2) +bus28|1)
#qualinv2 + qualinv3 + qualinv4+ region2:qualinv2 + region2:qualinv3  + region2:qualinv4

fit_int <- mnlogit(fm_int, mnlogit_dt_out, ncores=4, choiceVar = "alt")


#substitution of coefficients
multinom_int2 <- multinom_int
cf2 <- matrix(multinom_int2$wts, nrow=71) # davor 39 
fit_interaction.cf <- coef(fit_interaction)
cf2[2:nrow(cf2), 2:ncol(cf2)] <- (matrix(fit_interaction.cf,nrow=3))

# Substitution of probabilities
multinom_int2$wts <- c(cf2)
multinom_int2$fitted.values <- fit_interaction$probabilities


```


Compute effects
```{r}
#compute and manipulate all effects
library(effects)
#qualinv4
ef <- effect("region2:quali_nv", multinom_int2) #nur rural and urban und nur 1 und 2
ef <- as.data.frame(ef)

#numlic
ef2 <- effect("region2:numlic", multinom_int)
ef2 <- as.data.frame(ef2)


#income_numerical
ef3 <- effect("region2:income_numerical", multinom_int2)#bei rural nicht 1
ef3 <- as.data.frame(ef3)

#Csyes
ef4 <- effect("region2:CSyes", multinom_int2) #nursuburban, alle
temp <- ef4
ef4 <- as.data.frame(ef4)


ef5 <- effect("region2:workers", multinom_int2) # alles 
ef5 <- as.data.frame(ef5)
ef12 <- effect("region2:parttime", multinom_int2) # alles 
ef12 <- as.data.frame(ef12)

ef6 <- effect("region2:triplength_avg", multinom_int2) #nur suburban significant, alle levels
ef6 <- as.data.frame(ef6)

ef7 <- effect("region2:oldHH", multinom_int2) #nur rural, alle levels
ef7 <- as.data.frame(ef7)

ef8 <- effect("region2:hh_children", multinom_int2) #nur carownership 2 bei suburban, 2 und 3 bei rural
ef8 <- as.data.frame(ef8)


ef9 <- effect("region2:numped", multinom_int2) #bei rural level1 nicht (2 plots)
ef9 <- as.data.frame(ef9)


ef10 <- effect("region2:quali_opnv", multinom_int2) #bei rural level1 nicht (2 plots)
ef10 <- as.data.frame(ef10)

ef11 <- effect("region2:CSmultiple", multinom_int2) #bei rural level1 nicht (2 plots)
ef11 <- as.data.frame(ef11)

ef13 <- effect("region2:housing_type", multinom_int2) #bei rural level1 nicht (2 plots)
ef13 <- as.data.frame(ef13)

ef19 <- effect("region2:garage", multinom_int) #bei rural level1 nicht (2 plots)
ef19 <- as.data.frame(ef19)

ef14 <- effect("region2:metro28", multinom_int2) #bei rural level1 nicht (2 plots)
ef14 <- as.data.frame(ef14)

ef15 <- effect("region2:train28", multinom_int2) #bei rural level1 nicht (2 plots)
ef15 <- as.data.frame(ef15)

ef16 <- effect("region2:bus28", multinom_int2) #bei rural level1 nicht (2 plots)
ef16 <- as.data.frame(ef16)

ef17 <- effect("region2:tripsavg", multinom_int2) #bei rural level1 nicht (2 plots)
ef17 <- as.data.frame(ef17)

ef18 <- effect("region2:log(nummots1)", multinom_int) #bei rural level1 nicht (2 plots)
ef18 <- as.data.frame(ef18)

#effects plot normal mit plot
#quali_nv4: only urban rural significantnand only for levels 0 vs.1 and 0 vs. 2, other qualinvs not significant
#ef$variables$qualinv4$levels <- c("0", "4")
#plot(ef, multiline=TRUE, x.var = "qualinv4", rug=FALSE, colors = c("blue", "red", "orange", "transparent"))

#numlic
#plot(ef2, multiline=TRUE, x.var = "numlic", rug=FALSE, colors = c("blue", "red", "orange", "black"))

#income_numerical
#plot(effect("region2:income_numerical", multinom_int2), multiline=TRUE, x.var = "income_numerical", rug=FALSE)

#levels(ef$x$C) <- c("foo", "bar")

#https://stackoverflow.com/questions/20530232/change-factor-labels-on-effects-plot-in-r
```

Plots with ggplot - interaction terms
numlic
```{r}
#library(ggplot2)

#numlic 
Plot.numlic0<-ggplot(data=ef2, aes(x=numlic, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      #scale_color_manual(labels = c("urban","suburban", "rural"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=L.prob.X0, ymax=U.prob.X0),linetype=0,alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      labs(color = "region") +
      #coord_fixed(ratio=10)+
  scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.numlic0

Plot.numlic1<-ggplot(data=ef2, aes(x=numlic, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      #scale_color_manual(labels = c("urban","suburban", "rural"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=L.prob.X1, ymax=U.prob.X1),linetype=0,alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      labs(color = "region") +
      #coord_fixed(ratio=10)+
  scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.numlic1

Plot.numlic2<-ggplot(data=ef2, aes(x=numlic, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      #scale_color_manual(labels = c("urban","suburban", "rural"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=L.prob.X2, ymax=U.prob.X2),linetype=0,alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      labs(color = "region") +
     # coord_fixed(ratio=10)+
  scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.numlic2

Plot.numlic3<-ggplot(data=ef2, aes(x=numlic, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      #scale_color_manual(labels = c("urban","suburban", "rural"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=L.prob.X3, ymax=U.prob.X3),linetype=0,alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      labs(color = "region") +
      #coord_fixed(ratio=10)+
    scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.numlic3

```

```{r}
figure_numlic <- ggarrange(Plot.numlic0, Plot.numlic1, Plot.numlic2,Plot.numlic3,common.legend = TRUE, legend = "right", 
          labels = c("Zero cars", "One car", "Two cars","Three cars"),
          ncol = 2, nrow = 2)



annotate_figure(figure_numlic,
                top = text_grob("Number of license holders and region as predictors of car ownership", color = "black", size =                   14,),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Number of license holders"),
)

```

Income numerical

```{r}
#income (3 separate plot)
Plot.income0 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype=0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      labs(color = "region") +
      coord_fixed(ratio=10)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.income0

Plot.income1 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype=0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=10)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.income1

Plot.income2 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype=0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=10)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.income2


Plot.income3 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype=0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=8)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.income3

```

```{r}
figure_income <- ggarrange(Plot.income0, Plot.income1, Plot.income2,common.legend = TRUE, legend = "right", 
          labels = c("Zero cars", "One car", "Two cars"), vjust=7,
          ncol = 4, nrow = 1)



annotate_figure(figure_income,
                top = text_grob("Monthly income and region as predictors of car ownership", color = "black", size =                   14, vjust=5),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Monthly Income", vjust=-8),
)



```

qualinv
```{r}
#qualinv4
Plot.qualinv1 <-ggplot(data=ef, aes(x=quali_nv, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=12)+
      scale_y_continuous(limits=c(0,0.3),breaks = c(0.1,0.2,0.3))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualinv1

Plot.qualinv2 <-ggplot(data=ef, aes(x=quali_nv, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=4)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualinv2

Plot.qualinv3 <-ggplot(data=ef, aes(x=quali_nv, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
     labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=4)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualinv3

Plot.qualinv4 <-ggplot(data=ef, aes(x=quali_nv, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=4)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualinv4
```

```{r}
#library(ggpubr)
figure <- ggarrange(Plot.qualinv1, Plot.qualinv2, Plot.qualinv3,common.legend = TRUE, legend = "right", 
          labels = c("Zero cars", "One car", "Two cars"), vjust=8,
          ncol = 3, nrow = 1)

annotate_figure(figure,
                top = text_grob("Quality of public services and region as predictors of car ownership", color = "black", size = 14, vjust=6),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Quality of public services", vjust=-8),
)



```



quali_opnv # in rural und suburban from 1 to 2 not great difference, in urban already a difference between 1 and 2
```{r}
Plot.qualiopnv1 <-ggplot(data=ef10, aes(x=quali_opnv, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=12)+
      scale_y_continuous(limits=c(0,0.3),breaks = c(0.1,0.2,0.3))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualiopnv1

Plot.qualiopnv2 <-ggplot(data=ef10, aes(x=quali_opnv, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=4)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualiopnv2

Plot.qualiopnv3 <-ggplot(data=ef10, aes(x=quali_opnv, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
     labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=4)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        legend.position="bottom",
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualiopnv3

Plot.qualiopnv4 <-ggplot(data=ef10, aes(x=quali_opnv, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=4)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
              legend.direction = "horizontal",
              legend.position =c(0.35, 0.8),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualiopnv4
```

```{r}
figure1 <- ggarrange( Plot.qualinv1,Plot.qualinv2, Plot.qualinv3,legend="none",common.legend = TRUE,labels=c("     Zero cars",     "     One car", "     Two cars"), vjust=2,font.label = list(size = 10, just="left"),
          ncol = 3, nrow = 1)%>% gridExtra::grid.arrange(get_legend(Plot.qualiopnv3), heights = unit(c(60, 5), "mm"))

annotate_figure(figure1,
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Quality of public services", vjust=-11),
)

figure2 <- ggarrange( Plot.qualiopnv1,Plot.qualiopnv2, Plot.qualiopnv3,legend="none",common.legend = TRUE,labels=c("     Zero cars",     "     One car", "     Two cars"), vjust=4,font.label = list(size = 10, just="left"),
          ncol = 4, nrow = 1)%>% gridExtra::grid.arrange(get_legend(Plot.qualiopnv4), heights = unit(c(60, 5), "mm"))

annotate_figure(figure2,
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Quality of public transport", vjust=-11, just="right"),
)





```


Csyes
```{r}
#CSyes
Plot.cs0 <-ggplot(data=ef4, aes(x=CSyes, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,0.5),breaks = c(0.1,0.2,0.3,0.4,0.5))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),aspect.ratio=1)+
      scale_fill_grey()
#Plot.cs0

Plot.cs1 <-ggplot(data=ef4, aes(x=CSyes, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      scale_x_discrete(labels = c("0" = "No", "1" = "Yes"))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.cs1


Plot.cs2 <-ggplot(data=ef4, aes(x=CSyes, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.cs2

Plot.cs3<-ggplot(data=ef4, aes(x=CSyes, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(), aspect.ratio=1)+
      scale_fill_grey()
#Plot.cs3
```

```{r}
figure <- ggarrange(Plot.cs0, Plot.cs1, Plot.cs2,common.legend = TRUE, legend = "right", 
          labels = c("Zero cars", "One car", "Two cars"), vjust=8,
          ncol = 3, nrow = 1)

annotate_figure(figure,
                top = text_grob("Carsharing and region as predictors of car ownership", color = "black", size = 14, vjust=6),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Carsharing Subscription", vjust=-8),
)



```

workers
```{r}
#CSyes
Plot.work0 <-ggplot(data=ef5, aes(x=workers, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      labs(color = "region") +
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
  coord_fixed(ratio=3)+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.work0

Plot.work1 <-ggplot(data=ef5, aes(x=workers, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
  coord_fixed(ratio=3)+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.work1

Plot.work2 <-ggplot(data=ef5, aes(x=workers, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
  coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.work2

Plot.work3<-ggplot(data=ef5, aes(x=workers, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.work3
```

```{r}
figure_work <- ggarrange( Plot.work0,Plot.work1, Plot.work2, Plot.work3,common.legend = TRUE, legend = "none", 
          labels = c( "Zero cars","One car", "Two cars", "Three cars"),vjust=3,
          ncol = 4, nrow = 1)%>% gridExtra::grid.arrange(get_legend(Plot.qualiopnv3), heights = unit(c(60, 5), "mm"))


annotate_figure(figure_work,
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Number of workers", vjust=-11),
)
```

parttime

```{r}
Plot.parttime1 <-ggplot(data=ef12, aes(x=parttime, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()

Plot.parttime2 <-ggplot(data=ef12, aes(x=parttime, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()


Plot.parttime3 <-ggplot(data=ef12, aes(x=parttime, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
     labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()

Plot.parttime4 <-ggplot(data=ef12, aes(x=parttime, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
```

```{r}
figure_parttime <- ggarrange( Plot.parttime1,Plot.parttime2, Plot.parttime3, Plot.parttime4,common.legend = TRUE, legend = "none", 
          labels = c( "Zero cars","One car", "Two cars", "Three cars"),vjust=3,
          ncol = 4, nrow = 1)%>% gridExtra::grid.arrange(get_legend(Plot.qualiopnv3), heights = unit(c(60, 5), "mm"))


annotate_figure(figure_parttime,
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Number of parttime workers", vjust=-11),
)

```
triplength_avg
```{r}
Plot.trip0 <-ggplot(data=ef6, aes(x=triplength_avg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=30)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.trip0

Plot.trip1 <-ggplot(data=ef6, aes(x=triplength_avg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=30)+
      labs(color = "region") +
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.trip1

Plot.trip2 <-ggplot(data=ef6, aes(x=triplength_avg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=30)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.trip2

Plot.trip3<-ggplot(data=ef6, aes(x=triplength_avg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=30)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.trip3

```

```{r}
figure_trip <- ggarrange( Plot.trip1, Plot.trip2, common.legend = TRUE, legend = "right", 
          labels = c( "One car", "Two cars"), vjust=5,
          ncol = 2, nrow = 1)


annotate_figure(figure_trip,
                top = text_grob("Average triplength and region as predictors of car ownership", color = "black", size = 14, vjust=4),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Average triplength", vjust=-4),
)
```

Share old

```{r}
Plot.share0 <-ggplot(data=ef7, aes(x=oldHH, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region")+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,0.5),breaks = c(0.1,0.2,0.3,0.4))+
      #scale_x_continuous(limits=c(0,1),breaks = c(0.5))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.share0

Plot.share1 <-ggplot(data=ef7, aes(x=oldHH, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      labs(color = "region") +
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      #scale_x_continuous(limits=c(0,1),breaks = c(0.5))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.share1

Plot.share2 <-ggplot(data=ef7, aes(x=oldHH, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) +
      labs(color = "region")+
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      #scale_x_continuous(limits=c(0,1),breaks = c(0.5))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()


Plot.share3<-ggplot(data=ef7, aes(x=oldHH, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      labs(color = "region")+
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=4)+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      labs(color = "region")+
      scale_y_continuous(limits=c(0,0.5),breaks = c(0.1,0.2,0.3,0.4))+
      #scale_x_continuous(limits=c(0,1),breaks = c(0.5))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.share3
```

```{r}
figure_share <- ggarrange(Plot.share1, Plot.share2, common.legend = TRUE, legend = "right", 
          labels = c("One car", "Two cars", "Three cars"), vjust=5,
          ncol = 2, nrow = 1)


annotate_figure(figure_share,
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Type of Household", vjust=-6),
)
```


hh_children
```{r}
Plot.children0 <-ggplot(data=ef8, aes(x=hh_children, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      labs(color = "region")+
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=1)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.children0

Plot.children1 <-ggplot(data=ef8, aes(x=hh_children, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
  labs(color = "region")+
      ggtitle("")+
      coord_fixed(ratio=1)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.children1

Plot.children2 <-ggplot(data=ef8, aes(x=hh_children, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=1)+
  labs(color = "region")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.children2

Plot.children3<-ggplot(data=ef8, aes(x=hh_children, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
       ylab("")+
      xlab("")+
      ggtitle("")+
  labs(color = "region")+
      coord_fixed(ratio=1)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.children3
```

```{r}
figure_children <- ggarrange( Plot.children1, Plot.children2, common.legend = TRUE, legend = "right", 
          labels = c( "One car", "Two cars"), vjust=8,
          ncol = 2, nrow = 1)


annotate_figure(figure_children,
                top = text_grob("Children and region as predictors of car ownership", color = "black", size = 14, vjust=6),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Households with children", vjust=-10),
)
```


numped
```{r}
Plot.ped0 <-ggplot(data=ef9, aes(x=numped, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
  labs(color = "region")+
      coord_fixed(ratio=10)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.ped0

Plot.ped1 <-ggplot(data=ef9, aes(x=numped, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
  labs(color = "region")+
      coord_fixed(ratio=10)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.ped1

Plot.ped2 <-ggplot(data=ef9, aes(x=numped, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
  labs(color = "region")+
      coord_fixed(ratio=10)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.ped2

Plot.ped3<-ggplot(data=ef9, aes(x=numped, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
  labs(color = "region")+
      coord_fixed(ratio=10)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.ped3
```

```{r}
figure_ped <- ggarrange(Plot.ped0,Plot.ped1, Plot.ped2, common.legend = TRUE, legend = "right", 
          labels = c( "Zero cars","One car", "Two cars"), vjust=8,
          ncol = 3, nrow = 1)


annotate_figure(figure_ped,
                top = text_grob("Number of bicycles and region as predictors of car ownership", color = "black", size = 14, vjust=6),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Number of bicycles/pedelecs", vjust=-8),
)
```

housingtype

```{r}
Plot.housingtyp1 <-ggplot(data=ef13, aes(x=housing_type, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=6)+
      scale_y_continuous(limits=c(0,0.5),breaks = c(0.1,0.2,0.3,0.4))+
  scale_x_discrete(limits=c("singlefamily_h","multifamily_h", "apartmentbuilding"),labels = c("singlefamily_h" = "Singlefamily-Home", "multifamily_h" = "Multifamily-Home","apartmentbuilding" = "Apartmentbuilding"))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
              axis.text.x = element_text(angle=45,hjust=1),
        panel.grid.minor=element_blank())+
      scale_fill_grey()

Plot.housingtyp2 <-ggplot(data=ef13, aes(x=housing_type, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
  scale_x_discrete(limits=c("singlefamily_h","multifamily_h", "apartmentbuilding"),labels = c("singlefamily_h" = "Singlefamily-Home", "multifamily_h" = "Multifamily-Home","apartmentbuilding" = "Apartmentbuilding"))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
              axis.text.x = element_text(angle=45,hjust=1),
        panel.grid.minor=element_blank())+
      scale_fill_grey()


Plot.housingtyp3 <-ggplot(data=ef13, aes(x=housing_type, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
     labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
  scale_x_discrete(limits=c("singlefamily_h","multifamily_h", "apartmentbuilding"),labels = c("singlefamily_h" = "Singlefamily-Home", "multifamily_h" = "Multifamily-Home","apartmentbuilding" = "Apartmentbuilding"))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
              axis.text.x = element_text(angle=45,hjust=1),
        panel.grid.minor=element_blank())+
      scale_fill_grey()

Plot.housingtyp4 <-ggplot(data=ef13, aes(x=housing_type, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
     labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=3)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
  scale_x_discrete(limits=c("singlefamily_h","multifamily_h", "apartmentbuilding"),labels = c("singlefamily_h" = "Singlefamily-Home", "multifamily_h" = "Multifamily-Home","apartmentbuilding" = "Apartmentbuilding"))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
              axis.text.x = element_text(angle=45,hjust=1),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
```

```{r}
figure_housing <- ggarrange(Plot.housingtyp1, Plot.housingtyp2, Plot.housingtyp3,common.legend = TRUE, legend = "right", 
          labels = c("Zero cars", "One car", "Two cars"), vjust=6,
          ncol = 3, nrow = 1)

annotate_figure(figure_housing,
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Type of housing", color = "black",vjust=-5)
)

```

garage
```{r}
Plot.garage1 <-ggplot(data=ef19, aes(x=garage, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=4)+
      scale_y_continuous(limits=c(0,0.5),breaks = c(0.1,0.2,0.3,0.4))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()

Plot.garage2 <-ggplot(data=ef19, aes(x=garage, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()


Plot.garage3 <-ggplot(data=ef19, aes(x=garage, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
     labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()



Plot.garage4 <-ggplot(data=ef19, aes(x=garage, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
```

```{r}
figure_garage <- ggarrange( Plot.garage2, Plot.garage3,common.legend = TRUE, legend = "none", 
          labels = c("One car", "Two cars"), vjust=8,
          ncol = , nrow = 1)

annotate_figure(figure_garage,
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Availability of a garage", vjust=-10, just=c(1.5,0)),
)

figure_housing <- ggarrange(Plot.garage1, Plot.garage2, Plot.garage3,common.legend = TRUE, legend = "right", 
          labels = c("Zero cars", "One car", "Two cars"), vjust=9,
          ncol = 3, nrow = 1)

annotate_figure(figure_housing,
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Availabilty of a garage", color = "black",vjust=-9)
)

```



Not shown in thesis:

CS multiple

```{r}
Plot.csm0 <-ggplot(data=ef11, aes(x=CSmultiple, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,0.5),breaks = c(0.1,0.2,0.3,0.4,0.5))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),aspect.ratio=1)+
      scale_fill_grey()
#Plot.csm0

Plot.csm1 <-ggplot(data=ef11, aes(x=CSmultiple, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      scale_x_discrete(labels = c("0" = "No", "1" = "Yes"))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.csm1


Plot.csm2 <-ggplot(data=ef11, aes(x=CSmultiple, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.csm2

Plot.csm3<-ggplot(data=ef11, aes(x=CSmultiple, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(), aspect.ratio=1)+
      scale_fill_grey()
#Plot.cs3

```

```{r}
figure <- ggarrange(Plot.csm0, Plot.csm1, Plot.csm2,Plot.csm3,common.legend = TRUE, legend = "right", 
          labels = c("Zero cars", "One car", "Two cars"), vjust=8,
          ncol = 4, nrow = 1)

annotate_figure(figure,
                top = text_grob("Carsharing and region as predictors of car ownership", color = "black", size = 14, vjust=6),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Carsharing Subscription", vjust=-8),
)


```

trips
```{r}
Plot.tripsa0 <-ggplot(data=ef17, aes(x=tripsavg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,0.5),breaks = c(0.1,0.2,0.3,0.4,0.5))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),aspect.ratio=1)+
      scale_fill_grey()
#Plot.csm0

Plot.tripsa1 <-ggplot(data=ef17, aes(x=tripsavg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      scale_x_discrete(labels = c("0" = "No", "1" = "Yes"))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.csm1


Plot.tripsa2 <-ggplot(data=ef17, aes(x=tripsavg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.csm2

Plot.tripsa3<-ggplot(data=ef17, aes(x=tripsavg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(), aspect.ratio=1)+
      scale_fill_grey()
#Plot.cs3

```


log(nummots)

```{r}
Plot.mot0 <-ggplot(data=ef18, aes(x=nummots1, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      labs(color = "region") +
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,0.5),breaks = c(0.1,0.2,0.3,0.4,0.5))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),aspect.ratio=1)+
      scale_fill_grey()
#Plot.mot0

Plot.mot1 <-ggplot(data=ef18, aes(x=nummots1, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      scale_x_discrete(labels = c("0" = "No", "1" = "Yes"))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.csm1


Plot.mot2 <-ggplot(data=ef18, aes(x=nummots1, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      coord_fixed(ratio=2)+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
#Plot.csm2

Plot.mot3<-ggplot(data=ef18, aes(x=nummots1, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("")+
      xlab("")+
      ggtitle("")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(), aspect.ratio=1)+
      scale_fill_grey()
#Plot.cs3

```

```{r}
figure <- ggarrange(Plot.mot0, Plot.mot1, Plot.mot2,Plot.mot3,common.legend = TRUE, legend = "right", 
          labels = c("Zero cars", "One car", "Two cars"), vjust=8,
          ncol = 4, nrow = 1)

annotate_figure(figure,
                top = text_grob("Carsharing and region as predictors of car ownership", color = "black", size = 14, vjust=6),
                left = text_grob("Predicted Probability", color = "black", rot = 90),
                bottom = text_grob("Carsharing Subscription", vjust=-8),
)



```