---
title: "Plot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Effect plots model 1

Making mnlogit output the same as multinom (example)

```{r}
#Source: https://stackoverflow.com/questions/43623076/multinomial-logit-in-r-mlogit-versus-nnet/43697814

mlogitSample_test <- mlogit.data(HH_dt_model2, choice = "anzauto", shape = "wide") 

fm_test <- formula(anzauto ~ 1 | anzfs + region + hheink_imp + quali_nv + berufstaetige + householdtype+ CS + Weglänge_avg + anzmots + anzahl2039 + haustyp + quali_opnv + anzahl65 + Bildung + bahn28 + garage)
fit_test <- mnlogit(fm_test, mlogitSample_test, ncores=2, choiceVar = "alt")

fit_multitest <- multinom(anzauto ~ anzfs + region + hheink_imp+ quali_nv + berufstaetige + householdtype + CS +Weglänge_avg + anzmots + anzahl2039 + haustyp + quali_opnv + anzahl65 + Bildung + bahn28 + garage, data = HH_dt_model2)


fit_multitest <- multinom(anzauto ~ anzfs  + berufstaetige +, data = HH_dt_model2)
fm_test <- formula(anzauto ~ 1| anzfs + berufstaetige )
fit_test <- mnlogit(fm_test, mlogitSample_test, ncores=2, choiceVar = "alt")

#substitution of coefficients
fit_multitest2 <- fit_multitest
cf <- matrix(fit_multitest2$wts, nrow=4) # 1 + die anzahl an variablen
fit_test.cf <- coef(fit_test)
cf[2:nrow(cf), 2:ncol(cf)] <- (matrix(fit_test.cf,nrow=3)) #anzahl der levels der dependent variable -1

# Substitution of probabilities
fit_multitest2$wts <- c(cf)
fit_multitest2$fitted.values <- fit_test$probabilities

plot(effect("anzfs", fit_multitest2), multiline=TRUE, x.var = "anzfs", rug=FALSE)

# für andere
plot(effect("hheink_imp", fit_multinom), multiline=TRUE, rug=FALSE)

```


Making mnlogit output the same as multinom (normal)
```{r}
fit_multinom <- multinom(numcars ~ income_numerical +triplength_avg+ I(triplength_avg^2) + tripsavg +log(nummots1) + numped  + numch18 + numlic + I(numlic^2) + workers + parttime + share2039 + share4064 + CSyes + CSmultiple+ region2 + bus28 + train28 + metro28 + housing_type + garage + quali_opnv + quali_nv + hh_children, data = HH_dt_2_out)

fm_new <- formula(numcars ~   1| income_numerical +triplength_avg+ I(triplength_avg^2) + tripsavg +log(nummots1) + numped  + numch18 +numlic + I(numlic^2)  + workers + parttime + share2039 + share4064 + CSyes + CSmultiple + region2 + bus28 + train28 + metro28 + housing_type + garage + quali_opnv + quali_nv + hh_children|1)
fit_new <- mnlogit(fm_new, mnlogit_dt_out, ncores=4, choiceVar = "alt")


#substitution of coefficients
fit_multinom2 <- fit_multinom
cf2 <- matrix(fit_multinom2$wts, nrow=39) # davor 39 
fit_new.cf <- coef(fit_new)
cf2[2:nrow(cf2), 2:ncol(cf2)] <- (matrix(fit_new.cf,nrow=3))

# Substitution of probabilities
fit_multinom2$wts <- c(cf2)
fit_multinom2$fitted.values <- fit_new$probabilities

plot(effect("triplength_avg", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("income_numerical", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("sharedrivers", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("tripsavg", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("log(nummots1)", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("numped", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("numch18", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("workers", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("parttime", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("share2039", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("share4064", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("CSyes", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("CSmultiple", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("region2", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("bus28", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("metro28", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("train28", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("housing_type", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("garage", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("quali_opnv", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("quali_nv", fit_multinom2), multiline=TRUE, rug=FALSE)
plot(effect("hh_children", fit_multinom2), multiline=TRUE, rug=FALSE)

```


Effect plots interaction effects and normal effects

```{r}

multinom_int <- multinom(numcars ~ region2 + numlic + I(numlic^2) + region2:numlic + region2:I(numlic^2) + income_numerical +I(income_numerical^2)+ region2:income_numerical + region2:I(income_numerical^2) + qualinv2 + qualinv3 + qualinv4+ region2:qualinv2 + region2:qualinv3  + region2:qualinv4 + CSyes + region2:CSyes + workers+ I(workers^2)+region2:workers + triplength_avg+ I(triplength_avg^2)+ region2:triplength_avg+ region2:I(triplength_avg^2) + log(nummots1) + housing_type + garage + quali_opnv + share2039 + I(share2039^2)  +  region2:share2039 + region2:I(share2039^2) + share4064 + CSmultiple+ hh_children + region2:hh_children + metro28 +tripsavg + parttime + train28 +numped + I(numped^2) + region2:numped + region2:I(numped^2), data = HH_dt_2_out)

fm_int <- formula(numcars ~  1|region2 + numlic + I(numlic^2) + region2:numlic + region2:I(numlic^2) + income_numerical +I(income_numerical^2)+ region2:income_numerical + region2:I(income_numerical^2) + qualinv2 + qualinv3 + qualinv4+ region2:qualinv2 + region2:qualinv3  + region2:qualinv4 +CSyes + region2:CSyes + workers+ I(workers^2)+region2:workers + triplength_avg+ I(triplength_avg^2)+ region2:triplength_avg+ region2:I(triplength_avg^2) + log(nummots1) + housing_type + garage + quali_opnv + share2039 + I(share2039^2)  +  region2:share2039 + region2:I(share2039^2) + share4064 + CSmultiple+ hh_children + region2:hh_children + metro28 +tripsavg + parttime + train28 +numped + I(numped^2) + region2:numped + region2:I(numped^2) |1)

fit_int <- mnlogit(fm_int, mnlogit_dt_out, ncores=4, choiceVar = "alt")


#substitution of coefficients
multinom_int2 <- multinom_int
cf2 <- matrix(multinom_int2$wts, nrow=71) # davor 39 
fit_interaction.cf <- coef(fit_interaction)
cf2[2:nrow(cf2), 2:ncol(cf2)] <- (matrix(fit_interaction.cf,nrow=3))

# Substitution of probabilities
multinom_int2$wts <- c(cf2)
multinom_int2$fitted.values <- fit_interaction$probabilities

#compute and manipulate all effects

#qualinv4
ef <- effect("region2:qualinv4", multinom_int2) #nur rural and urban und nur 1 und 2
ef <- as.data.frame(ef)
ef <- filter(ef, !(region2 == "suburban"))
ef$qualinv4 = revalue(ef$qualinv4, c("0"="0", "1"="4"))

#numlic
ef2 <- effect("region2:numlic", multinom_int2,se=TRUE, confidence.level=.95, typical=mean)
ef2 <- as.data.frame(ef2)

#income_numerical
ef3 <- effect("region2:income_numerical", multinom_int2)#bei rural nicht 1
ef3 <- as.data.frame(ef3)
ef3_rural <- filter(ef3, region2 == "rural")
ef3_urban <- filter(ef3, region2 == "urban")
ef3_suburban <- filter(ef3, region2 == "suburban")

#Csyes
ef4 <- effect("region2:CSyes", multinom_int2) #nursuburban, alle
temp <- ef4
ef4 <- as.data.frame(ef4)


ef5 <- effect("region2:workers", multinom_int2) # alles 
ef5 <- as.data.frame(ef5)

ef6 <- effect("region2:triplength_avg", multinom_int2) #nur suburban significant, alle levels
ef6 <- as.data.frame(ef6)

ef7 <- effect("region2:share2039", multinom_int2) #nur rural, alle levels
ef7 <- as.data.frame(ef7)

ef8 <- effect("region2:hh_children", multinom_int2) #nur carownership 2 bei suburban, 2 und 3 bei rural
ef8 <- as.data.frame(ef8)


ef9 <- effect("region2:numped", multinom_int2) #bei rural level1 nicht (2 plots)
ef9 <- as.data.frame(ef9)


#effects plot normal mit plot
#quali_nv4: only urban rural significantnand only for levels 0 vs.1 and 0 vs. 2, other qualinvs not significant
#ef$variables$qualinv4$levels <- c("0", "4")
#plot(ef, multiline=TRUE, x.var = "qualinv4", rug=FALSE, colors = c("blue", "red", "orange", "transparent"))

#numlic
#plot(ef2, multiline=TRUE, x.var = "numlic", rug=FALSE, colors = c("blue", "red", "orange", "black"))

#income_numerical
#plot(effect("region2:income_numerical", multinom_int2), multiline=TRUE, x.var = "income_numerical", rug=FALSE)

#levels(ef$x$C) <- c("foo", "bar")

#https://stackoverflow.com/questions/20530232/change-factor-labels-on-effects-plot-in-r

```


Plots with ggplot
```{r}
library(ggplot2)

#numlic 
Plot.numlic<-ggplot(data=ef2, aes(x=numlic, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      #scale_color_manual(labels = c("urban","suburban", "rural"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=L.prob.X0, ymax=U.prob.X0),linetype=0,alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2)+
      #geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2)+
      ylab("Probability")+
      xlab("Number of Licenses")+
      ggtitle("Number of Licenses and region as predictors of the number of cars owned")+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.numlic



```




Income numerical

```{r}
#income (3 separate plot)
Plot.income0 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype=0)+
      ylab("Probability")+
      xlab("Income")+
      ggtitle("0 cars: Income and region as predictors")+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.income0

Plot.income1 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype=0)+
      ylab("Probability")+
      xlab("Income")+
      ggtitle("1 cars: Income and region as predictors")+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.income1

Plot.income2 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype=0)+
      ylab("Probability")+
      xlab("Income")+
      ggtitle("1 cars: Income and region as predictors")+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.income2

Plot.income2 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype=0)+
      ylab("Probability")+
      xlab("Income")+
      ggtitle("2 cars: Income and region as predictors")+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.income2

Plot.income3 <-ggplot(data=ef3, aes(x=income_numerical, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #geom_line(aes(y=prob.X3, color ="prob.X3"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype=0)+
      ylab("Probability")+
      xlab("Income")+
      ggtitle("3 cars: Income and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.income3




```


qualinv
```{r}
#qualinv4
Plot.qualinv4 <-ggplot(data=ef, aes(x=qualinv4, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Quality of public services")+
      ggtitle("0 cars: Quality of public services and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualinv4

Plot.qualinv4 <-ggplot(data=ef, aes(x=qualinv4, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Quality of public services")+
      ggtitle("0 cars: Quality of public services and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualinv4

Plot.qualinv4 <-ggplot(data=ef, aes(x=qualinv4, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Quality of public services")+
      ggtitle("0 cars: Quality of public services and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualinv4

Plot.qualinv4 <-ggplot(data=ef, aes(x=qualinv4, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Quality of public services")+
      ggtitle("0 cars: Quality of public services and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.qualinv4
```


Csyes
```{r}
#CSyes
Plot.cs0 <-ggplot(data=ef4, aes(x=CSyes, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Carsharing subscription")+
      ggtitle("0 cars: Carsharing and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.cs0

Plot.cs1 <-ggplot(data=ef4, aes(x=CSyes, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Carsharing subscription")+
      ggtitle("1 cars: Carsharing and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.cs1

Plot.cs2 <-ggplot(data=ef4, aes(x=CSyes, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Carsharing subscription")+
      ggtitle("2 cars: Carsharing and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.cs2

Plot.cs3<-ggplot(data=ef4, aes(x=CSyes, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Carsharing subscription")+
      ggtitle("3 cars: Carsharing and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.cs3
```

workers
```{r}
#CSyes
Plot.work0 <-ggplot(data=ef5, aes(x=workers, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Number of workers")+
      ggtitle("0 cars: Workers and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.work0

Plot.work1 <-ggplot(data=ef5, aes(x=workers, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Number of workers")+
      ggtitle("1 cars: Workers and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.work1

Plot.work2 <-ggplot(data=ef5, aes(x=workers, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Number of workers")+
      ggtitle("2 cars: Workers and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.work2

Plot.work3<-ggplot(data=ef5, aes(x=workers, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Number of workers")+
      ggtitle("3 cars: Workers and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.work3
```

triplength_avg
```{r}
Plot.trip0 <-ggplot(data=ef6, aes(x=triplength_avg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Average triplength")+
      ggtitle("0 cars: Average triplength and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.trip0

Plot.trip1 <-ggplot(data=ef6, aes(x=triplength_avg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Average triplength")+
      ggtitle("0 cars: Average triplength and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.trip1

Plot.trip2 <-ggplot(data=ef6, aes(x=triplength_avg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Average triplength")+
      ggtitle("0 cars: Average triplength and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.trip2

Plot.trip3<-ggplot(data=ef6, aes(x=triplength_avg, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Average triplength")+
      ggtitle("0 cars: Average triplength and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.trip3

```

share2039
```{r}
Plot.share0 <-ggplot(data=ef7, aes(x=share2039, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Share of 20 to 39 year olds")+
      ggtitle("0 cars: Share of 20- to 39 year olds and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.share0

Plot.share1 <-ggplot(data=ef7, aes(x=share2039, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Share of 20 to 39 year olds")+
      ggtitle("1 cars: Share of 20- to 39 year olds and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.share1

Plot.share2 <-ggplot(data=ef7, aes(x=share2039, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Share of 20 to 39 year olds")+
      ggtitle("2 cars: Share of 20- to 39 year olds and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.share2

Plot.share3<-ggplot(data=ef7, aes(x=share2039, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Share of 20 to 39 year olds")+
      ggtitle("3 cars: Share of 20- to 39 year olds and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.share3
```

hh_children
```{r}
Plot.children0 <-ggplot(data=ef8, aes(x=hh_children, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("CHousehold with children")+
      ggtitle("0 cars: Households with children and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.children0

Plot.children1 <-ggplot(data=ef8, aes(x=hh_children, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("CHousehold with children")+
      ggtitle("0 cars: Households with children and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.children1

Plot.children2 <-ggplot(data=ef8, aes(x=hh_children, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("CHousehold with children")+
      ggtitle("0 cars: Households with children and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.children2

Plot.children3<-ggplot(data=ef8, aes(x=hh_children, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("CHousehold with children")+
      ggtitle("0 cars: Households with children and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.children3
```


numped
```{r}
Plot.ped0 <-ggplot(data=ef9, aes(x=numped, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X0)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X0-se.prob.X0, ymax=prob.X0+se.prob.X0),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Number of pedelecs and bikes")+
      ggtitle("0 cars: Number of pedelecs/bikes and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.ped0

Plot.ped1 <-ggplot(data=ef9, aes(x=numped, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X1)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X1-se.prob.X1, ymax=prob.X1+se.prob.X1),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Number of pedelecs and bikes")+
      ggtitle("1 cars: Number of pedelecs/bikes and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.ped1

Plot.ped2 <-ggplot(data=ef9, aes(x=numped, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X2)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X2-se.prob.X2, ymax=prob.X2+se.prob.X2),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Number of pedelecs and bikes")+
      ggtitle("2 cars: Number of pedelecs/bikes and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.ped2

Plot.ped3<-ggplot(data=ef9, aes(x=numped, group=region2, color=region2))+
#For ylim, specify the range of your DV (in our case, 0-4)
      #facet_wrap(~region2)+
      geom_line(aes(y=prob.X3)) + 
      #geom_line(aes(y=prob.X1, color="prob.X1")) + 
      #geom_line(aes(y=prob.X2, color ="prob.X2"))+
      #scale_color_manual(labels = c("0 car","1 car", "2 cars"),values= c("blue", "red", "orange"))+
      geom_ribbon(aes(ymin=prob.X3-se.prob.X3, ymax=prob.X3+se.prob.X3),alpha=.2, linetype =0)+
      ylab("Probability")+
      xlab("Number of pedelecs and bikes")+
      ggtitle("3 cars: Number of pedelecs/bikes and region as predictors")+
      scale_y_continuous(limits=c(0,1),breaks = c(0.2,0.4,0.6,0.8))+
      theme_bw()+ 
        theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank())+
      scale_fill_grey()
Plot.ped3
```



Accuracy

```{r}
install.packages('interplot')
library(interplot)
# https://cran.r-project.org/web/packages/interplot/vignettes/interplot-vignette.html

# https://cran.r-project.org/web/packages/sjPlot/vignettes/plot_marginal_effects.html

#https://lost-stats.github.io/Presentation/marginal_effects_plots_for_interactions_with_continuous_variables.html

#interplot(m = fit_multinom, var1 = "trips", var2 = "income_numerical")


```
```{r}
ProbCat <- predict(fit_new)
categHat <- levels(HH_dt_2_out$numcars)[max.col(ProbCat)]

facHat <- factor(categHat, levels=levels(HH_dt_2_out$numcars))
cTab   <- table(HH_dt_2_out$numcars, facHat, dnn=c("Ycateg", "facHat"))
addmargins(cTab)

(CCR <- sum(diag(cTab)) / sum(cTab))


# mit interaction model 
ProbCat2 <- predict(fit_interaction)
categHat <- levels(HH_dt_2_out$numcars)[max.col(ProbCat2)]

facHat <- factor(categHat, levels=levels(HH_dt_2_out$numcars))
cTab   <- table(HH_dt_2_out$numcars, facHat, dnn=c("Ycateg", "facHat"))
addmargins(cTab)

(CCR <- sum(diag(cTab)) / sum(cTab))


```



```{r}

unstandardizedResiduals <- resid(fit_new)
 #get standardized values
standardizedResiduals <- (unstandardizedResiduals - mean(unstandardizedResiduals)) / sd(unstandardizedResiduals)



x <- as.data.frame(standardizedResiduals)
summary(x)

#keine standardized residuals > 3 or < -3

```

